### ISSUE TITLE
Images not resolved from stylesheet

### ISSUE THREAD

**Issue by jdwillemse** [ueno-llc/starter-kit-universally#99]
What path do I need to use in my stylesheets to access an image in the images folder?

From the script files the path is what I'd expect `assets/images/file.png`, but this does not work from .scss files.

**Comment by jdwillemse** [comment]
resolved this by adding ~ to the path `~assets/images/file.png`

**Comment by jeremybarbet** [comment]
Hi!

You shouldn't have to use the `~` symbol to import images from `assets/images` directory. Here are two examples of urls with both png and svg.

```css
.images {
  &__png {
    ...
    background-image: url('assets/images/favicon.png');
  }

  &__svg {
    ...
    background-image: url('!file-loader!assets/images/favicon.svg');
  }
}
```

The only difference comes when you have to import svg file, at the moment you have to prepend `!file-loader!` to make it works.
